# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './tuner.ui'
#
# Created: Wed Aug  1 11:48:19 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tuner(object):
    def setupUi(self, Tuner):
        Tuner.setObjectName("Tuner")
        Tuner.resize(849, 643)
        self.tunerLO = QtGui.QGroupBox(Tuner)
        self.tunerLO.setGeometry(QtCore.QRect(10, 400, 711, 151))
        self.tunerLO.setObjectName("tunerLO")
        self.loDiv = QtGui.QLineEdit(self.tunerLO)
        self.loDiv.setEnabled(False)
        self.loDiv.setGeometry(QtCore.QRect(370, 20, 71, 21))
        self.loDiv.setObjectName("loDiv")
        self.label_7 = QtGui.QLabel(self.tunerLO)
        self.label_7.setGeometry(QtCore.QRect(17, 24, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tunerLO)
        self.label_8.setGeometry(QtCore.QRect(339, 23, 31, 16))
        self.label_8.setObjectName("label_8")
        self.loInfo = QtGui.QLineEdit(self.tunerLO)
        self.loInfo.setGeometry(QtCore.QRect(39, 20, 281, 21))
        self.loInfo.setObjectName("loInfo")
        self.loSet = QtGui.QPushButton(self.tunerLO)
        self.loSet.setGeometry(QtCore.QRect(630, 112, 71, 25))
        self.loSet.setObjectName("loSet")
        self.loGet = QtGui.QPushButton(self.tunerLO)
        self.loGet.setGeometry(QtCore.QRect(534, 111, 71, 25))
        self.loGet.setObjectName("loGet")
        self.label_9 = QtGui.QLabel(self.tunerLO)
        self.label_9.setGeometry(QtCore.QRect(460, 20, 21, 20))
        self.label_9.setObjectName("label_9")
        self.loN = QtGui.QLineEdit(self.tunerLO)
        self.loN.setEnabled(False)
        self.loN.setGeometry(QtCore.QRect(480, 20, 81, 21))
        self.loN.setObjectName("loN")
        self.tunerR0 = QtGui.QLineEdit(self.tunerLO)
        self.tunerR0.setEnabled(False)
        self.tunerR0.setGeometry(QtCore.QRect(620, 20, 81, 21))
        self.tunerR0.setObjectName("tunerR0")
        self.tunerR1 = QtGui.QLineEdit(self.tunerLO)
        self.tunerR1.setEnabled(False)
        self.tunerR1.setGeometry(QtCore.QRect(620, 50, 81, 21))
        self.tunerR1.setObjectName("tunerR1")
        self.tunerR2 = QtGui.QLineEdit(self.tunerLO)
        self.tunerR2.setEnabled(False)
        self.tunerR2.setGeometry(QtCore.QRect(620, 80, 81, 21))
        self.tunerR2.setObjectName("tunerR2")
        self.label_11 = QtGui.QLabel(self.tunerLO)
        self.label_11.setGeometry(QtCore.QRect(592, 23, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.tunerLO)
        self.label_12.setGeometry(QtCore.QRect(593, 53, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.tunerLO)
        self.label_13.setGeometry(QtCore.QRect(593, 84, 21, 16))
        self.label_13.setObjectName("label_13")
        self.tunerPA = QtGui.QGroupBox(Tuner)
        self.tunerPA.setGeometry(QtCore.QRect(10, 279, 351, 121))
        self.tunerPA.setObjectName("tunerPA")
        self.paSet = QtGui.QPushButton(self.tunerPA)
        self.paSet.setGeometry(QtCore.QRect(270, 80, 71, 25))
        self.paSet.setObjectName("paSet")
        self.paGet = QtGui.QPushButton(self.tunerPA)
        self.paGet.setGeometry(QtCore.QRect(271, 47, 71, 25))
        self.paGet.setObjectName("paGet")
        self.paInfo = QtGui.QLineEdit(self.tunerPA)
        self.paInfo.setGeometry(QtCore.QRect(59, 13, 281, 21))
        self.paInfo.setObjectName("paInfo")
        self.paRFVGA = QtGui.QComboBox(self.tunerPA)
        self.paRFVGA.setGeometry(QtCore.QRect(59, 75, 191, 22))
        self.paRFVGA.setObjectName("paRFVGA")
        self.label = QtGui.QLabel(self.tunerPA)
        self.label.setGeometry(QtCore.QRect(19, 17, 31, 16))
        self.label.setObjectName("label")
        self.label_3 = QtGui.QLabel(self.tunerPA)
        self.label_3.setGeometry(QtCore.QRect(9, 79, 41, 20))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtGui.QLabel(self.tunerPA)
        self.label_2.setGeometry(QtCore.QRect(19, 51, 31, 16))
        self.label_2.setObjectName("label_2")
        self.paPA1 = QtGui.QComboBox(self.tunerPA)
        self.paPA1.setGeometry(QtCore.QRect(59, 46, 191, 22))
        self.paPA1.setObjectName("paPA1")
        self.tunerLNA = QtGui.QGroupBox(Tuner)
        self.tunerLNA.setGeometry(QtCore.QRect(380, 279, 341, 121))
        self.tunerLNA.setObjectName("tunerLNA")
        self.lnaLNA2 = QtGui.QComboBox(self.tunerLNA)
        self.lnaLNA2.setGeometry(QtCore.QRect(50, 80, 191, 22))
        self.lnaLNA2.setObjectName("lnaLNA2")
        self.lnaInfo = QtGui.QLineEdit(self.tunerLNA)
        self.lnaInfo.setGeometry(QtCore.QRect(50, 15, 281, 21))
        self.lnaInfo.setObjectName("lnaInfo")
        self.lnaSet = QtGui.QPushButton(self.tunerLNA)
        self.lnaSet.setGeometry(QtCore.QRect(260, 82, 71, 25))
        self.lnaSet.setObjectName("lnaSet")
        self.label_4 = QtGui.QLabel(self.tunerLNA)
        self.label_4.setGeometry(QtCore.QRect(10, 15, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtGui.QLabel(self.tunerLNA)
        self.label_6.setGeometry(QtCore.QRect(10, 84, 31, 20))
        self.label_6.setObjectName("label_6")
        self.lnaGet = QtGui.QPushButton(self.tunerLNA)
        self.lnaGet.setGeometry(QtCore.QRect(260, 49, 71, 25))
        self.lnaGet.setObjectName("lnaGet")
        self.lnaLNA1 = QtGui.QComboBox(self.tunerLNA)
        self.lnaLNA1.setGeometry(QtCore.QRect(50, 48, 191, 22))
        self.lnaLNA1.setObjectName("lnaLNA1")
        self.label_5 = QtGui.QLabel(self.tunerLNA)
        self.label_5.setGeometry(QtCore.QRect(10, 53, 31, 16))
        self.label_5.setObjectName("label_5")
        self.tunerReg = QtGui.QGroupBox(Tuner)
        self.tunerReg.setGeometry(QtCore.QRect(10, 10, 711, 261))
        self.tunerReg.setObjectName("tunerReg")
        self.groupBox = QtGui.QGroupBox(Tuner)
        self.groupBox.setGeometry(QtCore.QRect(20, 450, 561, 51))
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 25, 21, 16))
        self.label_10.setObjectName("label_10")
        self.loStartEn = QtGui.QCheckBox(self.groupBox)
        self.loStartEn.setGeometry(QtCore.QRect(146, 20, 51, 20))
        self.loStartEn.setObjectName("loStartEn")
        self.loEndEn = QtGui.QCheckBox(self.groupBox)
        self.loEndEn.setGeometry(QtCore.QRect(288, 20, 51, 20))
        self.loEndEn.setObjectName("loEndEn")
        self.loFreq = QtGui.QComboBox(self.groupBox)
        self.loFreq.setGeometry(QtCore.QRect(35, 20, 81, 22))
        self.loFreq.setObjectName("loFreq")
        self.loEnd = QtGui.QLineEdit(self.groupBox)
        self.loEnd.setGeometry(QtCore.QRect(338, 19, 71, 21))
        self.loEnd.setObjectName("loEnd")
        self.loSearch = QtGui.QPushButton(self.groupBox)
        self.loSearch.setGeometry(QtCore.QRect(480, 18, 71, 25))
        self.loSearch.setObjectName("loSearch")
        self.loStart = QtGui.QLineEdit(self.groupBox)
        self.loStart.setGeometry(QtCore.QRect(203, 20, 71, 21))
        self.loStart.setObjectName("loStart")

        self.retranslateUi(Tuner)
        QtCore.QMetaObject.connectSlotsByName(Tuner)

    def retranslateUi(self, Tuner):
        Tuner.setWindowTitle(QtGui.QApplication.translate("Tuner", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tunerLO.setTitle(QtGui.QApplication.translate("Tuner", "LO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Tuner", "LO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Tuner", "div", None, QtGui.QApplication.UnicodeUTF8))
        self.loSet.setText(QtGui.QApplication.translate("Tuner", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.loGet.setText(QtGui.QApplication.translate("Tuner", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Tuner", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Tuner", "R0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Tuner", "R1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Tuner", "R2", None, QtGui.QApplication.UnicodeUTF8))
        self.tunerPA.setTitle(QtGui.QApplication.translate("Tuner", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.paSet.setText(QtGui.QApplication.translate("Tuner", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.paGet.setText(QtGui.QApplication.translate("Tuner", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Tuner", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Tuner", "RFVGA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Tuner", "PA1", None, QtGui.QApplication.UnicodeUTF8))
        self.tunerLNA.setTitle(QtGui.QApplication.translate("Tuner", "LNA", None, QtGui.QApplication.UnicodeUTF8))
        self.lnaSet.setText(QtGui.QApplication.translate("Tuner", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Tuner", "LNA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Tuner", "LNA2", None, QtGui.QApplication.UnicodeUTF8))
        self.lnaGet.setText(QtGui.QApplication.translate("Tuner", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Tuner", "LNA1", None, QtGui.QApplication.UnicodeUTF8))
        self.tunerReg.setTitle(QtGui.QApplication.translate("Tuner", "Tuner Register", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Tuner", "LO Freq", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Tuner", "LO", None, QtGui.QApplication.UnicodeUTF8))
        self.loStartEn.setText(QtGui.QApplication.translate("Tuner", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.loEndEn.setText(QtGui.QApplication.translate("Tuner", "end", None, QtGui.QApplication.UnicodeUTF8))
        self.loSearch.setText(QtGui.QApplication.translate("Tuner", "Search", None, QtGui.QApplication.UnicodeUTF8))

